name = "precursus"
main = "worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./"
binding = "ASSETS"

[[kv_namespaces]]
binding = "PRECURSUS_KV"
id = "98650f2d900c41a5a516bdc5fcac876d"

[triggers]
crons = ["0 13 * * 1"]
